version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch
      - seed
    networks:
      - app-network

  seed:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && node dist/scripts/seed.js"
    depends_on:
      - redis
      - elasticsearch
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch_tmp:/tmp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
